app = "midday-api"
primary_region = "fra"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3_000
min_machines_running = 3
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 8
memory = "4gb"
