name: Beta Deployment - Desktop

on:
  workflow_dispatch:
    inputs:
      force_release:
        description: Make a release
        type: boolean
        default: false

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: tauri-apps/tauri-action@v0
        working-directory: ./apps/desktop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MIDDAY_ENV: staging
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }} --config src-tauri/tauri.staging.conf.json