name: Fly Deploy
permissions:
  contents: read
on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
      - packages/**
      - "!packages/email/**"
      - "!packages/ui/**"
jobs:
  deploy:
    name: 🚀 Deploy to Fly
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: 🔦 Run linter
        run: bun run lint --filter=@midday/api
      - name: 🪐 Check TypeScript
        run: bun run typecheck --filter=@midday/api
      - name: 🧪 Run unit tests
        run: bun run test
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --dockerfile apps/api/Dockerfile --config apps/api/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}